# Generated by Django 4.2.3 on 2024-01-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_pledge_supporter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Agriculture', 'Agriculture'), ('Architecture, Construction & Planning', 'Architecture, Construction & Planning'), ('Business Management & Entrepreneurship', 'Business Management & Entrepreneurship'), ('Creative arts & Design', 'Creative arts & Design'), ('Teaching, Education & Training', 'Teaching, Education & Training'), ('Engineering, Automation & Technology', 'Engineering, Automation & Technology'), ('Environmental Science & Sustainability', 'Environmental Science & Sustainability'), ('Health, Medicine, Psychology', 'Health, Medicine, Psychology'), ('IT and Computing', 'IT and Computing'), ('Law, Paralegal', 'Law, Paralegal'), ('Media & Communications', 'Media & Communications'), ('Personal Care, Beauty & Hair, Fitness', 'Personal Care, Beauty & Hair, Fitness'), ('Sciences and Mathematics', 'Sciences and Mathematics'), ('Society, Culture & Humanities', 'Society, Culture & Humanities'), ('Travel, Tourism & Hospitality', 'Travel, Tourism & Hospitality'), ('Veterinary Medicine', 'Veterinary Medicine'), ('Other', 'Other')], max_length=200)),
            ],
        ),
    ]
