# Generated by Django 4.2.3 on 2024-01-26 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(default='AGRI', on_delete=django.db.models.deletion.CASCADE, to='projects.category'),
        ),
    ]
