# Generated by Django 4.2.3 on 2024-01-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('Agriculture', 'Agriculture'), ('Architecture, Construction & Planning', 'Architecture, Construction & Planning'), ('Business Management & Entrepreneurship', 'Business Management & Entrepreneurship'), ('Creative arts & Design', 'Creative arts & Design'), ('Teaching, Education & Training', 'Teaching, Education & Training'), ('Engineering, Automation & Technology', 'Engineering, Automation & Technology'), ('Environmental Science & Sustainability', 'Environmental Science & Sustainability'), ('Health, Medicine, Psychology', 'Health, Medicine, Psychology'), ('IT and Computing', 'IT and Computing'), ('Law, Paralegal', 'Law, Paralegal'), ('Media & Communications', 'Media & Communications'), ('Personal Care, Beauty & Hair, Fitness', 'Personal Care, Beauty & Hair, Fitness'), ('Sciences and Mathematics', 'Sciences and Mathematics'), ('Society, Culture & Humanities', 'Society, Culture & Humanities'), ('Travel, Tourism & Hospitality', 'Travel, Tourism & Hospitality'), ('Veterinary Medicine', 'Veterinary Medicine'), ('Other', 'Other')], default='Agriculture', max_length=200),
        ),
    ]
