# Generated by Django 4.2.3 on 2024-01-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_category_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('AGRI', 'Agriculture'), ('ARCHITECTURE', 'Architecture, Construction & Planning'), ('BUSINESS', 'Business Management & Entrepreneurship'), ('CREATIVE', 'Creative arts & Design'), ('EDUCATION', 'Teaching, Education & Training'), ('ENGINEERING', 'Engineering, Automation & Technology'), ('ENVIRONMENTAL', 'Environmental Science & Sustainability'), ('HEALTH', 'Health, Medicine, Psychology'), ('IT', 'IT and Computing'), ('LAW', 'Law, Paralegal'), ('MEDIA', 'Media & Communications'), ('PERSONAL', 'Personal Care, Beauty & Hair, Fitness'), ('SCIENCES', 'Sciences and Mathematics'), ('SOCIETY', 'Society, Culture & Humanities'), ('TRAVEL', 'Travel, Tourism & Hospitality'), ('VET', 'Veterinary Medicine'), ('OTHER', 'Other')], default='AGRI', max_length=200),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
